[build]
  command = "npm run build"
  publish = "frontend/dist"
  functions = "netlify/functions"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200